apiVersion: v1
kind: Service
metadata:
  name: mydevops-service
spec:
  selector:
    app: mydevops
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
