version: '3.7'

services:
  mysql:
    # was 5.5.55
    image: mysql:5.7.26
    container_name: mysql
    network_mode: bridge
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: *******
      MYSQL_ROOT_HOST: '%'
    ports:
      - 10.165.15.162:3306:3306
    volumes:
      - var_mysql:/var/lib/mysql
      - /stacks/mysql/log:/var/log/mysql
      - /stacks/mysql/10-mydevops.cnf:/etc/mysql/conf.d/extras.cnf
    command:
      - "--user=mysql"

volumes:
  var_mysql:
