version: '3.7'

services:
  mysql:
    # was 5.5.55
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ******
      MYSQL_ROOT_HOST: '%'
    ports:
      - 10.0.1.142:3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /stacks/mysql/log:/var/log/mysql
      - /stacks/mysql/extras.cnf:/etc/mysql/conf.d/extras.cnf
##      - /stacks/mysql/extras.cnf:/etc/my.cnf.d/extras.cnf
    command:
      - "--user=mysql"
    networks:
      default:
        ipv4_address: 10.0.1.3

networks:
  default:
    external: true
    attachable: true
    name: confluence
