name: publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ebisundarsingh
  IMAGE_NAME: mydevops-web

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.PAT }} | docker login -u ebenezeryeshua@gmail.com --password-stdin
        - name: Build and Publish
          run: |
            docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
    deploy:
        needs: publish
        name: deploy image
        runs-on: ubuntu-latest

        steps:
          - name: rsync the docker-compose.yml file
            uses: actions/checkout@v3
          - name: rsync deployments
            uses: burnett01/rsync-deployments@7.0.1
            with:
              switches: -avzr --delete
              path: ./docker-compose.yml
              remote_path: /data/production
              remote_host: ${{ secrets.SSH_HOST }}
              remote_user: ${{ secrets.SSH_USER }}
              remote_port: ${{ secrets.SSH_PORT }}
              remote_key: ${{ secrets.SSH_PRIVATE_KEY }}           
          - name: List files in the repository
            run: |
              ls ./
          - name: install ssh keys and execute commands
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              password: ${{ secrets.SSH_PASSWORD }}
              port: ${{ secrets.SSH_PORT }}
              script: cd /data/production/ && docker compose build && docker compose pull &&  docker compose up -d && exit
